# Generated by Django 4.0 on 2022-01-31 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('book_guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GBooking',
            fields=[
                ('Gbooking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nationality', models.CharField(max_length=200)),
                ('visit', models.CharField(max_length=100)),
                ('group_size', models.CharField(max_length=200)),
                ('days', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('More_details', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_guide.book_guide')),
            ],
            options={
                'db_table': 'guide_booked',
            },
        ),
    ]
