# Generated by Django 4.0 on 2022-01-21 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VBooking',
            fields=[
                ('vbooking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_plan', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.vdetails')),
            ],
            options={
                'db_table': 'boking_vehicle',
            },
        ),
    ]
