# Generated by Django 4.0 on 2022-02-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBooking',
            fields=[
                ('TBooking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('group_size', models.CharField(max_length=100)),
                ('arrival_data', models.DateField()),
                ('other_details', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trippackage')),
            ],
            options={
                'db_table': 'book_trip',
            },
        ),
    ]
