# Generated by Django 4.0 on 2022-01-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VDetails',
            fields=[
                ('v_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('V_model', models.CharField(max_length=200)),
                ('v_color', models.CharField(max_length=100)),
                ('v_rent', models.CharField(max_length=100)),
                ('v_purchase', models.DateField()),
                ('v_image', models.FileField(upload_to='rent')),
            ],
            options={
                'db_table': 'rent',
            },
        ),
    ]
