# Generated by Django 4.0 on 2022-01-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VDetails',
            fields=[
                ('vehicle_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Vehicle_model', models.CharField(max_length=200)),
                ('vehicle_color', models.CharField(max_length=100)),
                ('vehicle_rent', models.CharField(max_length=100)),
                ('vehicle_purchase', models.DateField()),
                ('vehicle_image', models.FileField(upload_to='vehicle')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
