# Generated by Django 3.0.2 on 2022-01-30 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBooking',
            fields=[
                ('fbooking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=100)),
                ('tickets', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Book_guide')),
            ],
            options={
                'db_table': 'book_flight',
            },
        ),
    ]
