# Generated by Django 4.0 on 2022-01-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_event',
            fields=[
                ('event_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('event_email', models.CharField(max_length=100)),
                ('event_phone', models.CharField(max_length=10)),
                ('event_message', models.CharField(max_length=500)),
                ('event_budget', models.CharField(max_length=100)),
                ('purpose_event', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
            ],
            options={
                'db_table': 'book_event',
            },
        ),
    ]
