# Generated by Django 4.0 on 2022-01-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_guide',
            fields=[
                ('flight_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('flight_name', models.CharField(max_length=200)),
                ('flight_from', models.CharField(max_length=100)),
                ('flight_to', models.CharField(max_length=100)),
                ('flight_way', models.CharField(max_length=100)),
                ('flight_money', models.CharField(max_length=500)),
                ('flight_date', models.DateField()),
                ('flight_time', models.TimeField()),
            ],
            options={
                'db_table': 'flights',
            },
        ),
    ]
