# Generated by Django 4.0 on 2022-01-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('customer_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
