# Generated by Django 4.0 on 2022-01-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBooking',
            fields=[
                ('fbooking_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=100)),
                ('tickets', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('flights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.book_guide')),
            ],
            options={
                'db_table': 'book_flight',
            },
        ),
    ]
