# Generated by Django 4.0 on 2022-01-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('Event_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=200)),
                ('last', models.CharField(max_length=200)),
                ('e_email', models.CharField(max_length=100)),
                ('e_phone', models.CharField(max_length=10)),
                ('e_message', models.CharField(max_length=500)),
                ('e_budget', models.CharField(max_length=100)),
                ('e_purpose', models.CharField(max_length=200)),
                ('e_date', models.DateField()),
            ],
            options={
                'db_table': 'Event',
            },
        ),
    ]
