# Generated by Django 4.0 on 2022-02-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=200)),
                ('food_place', models.CharField(max_length=200)),
                ('food_details', models.CharField(max_length=200)),
                ('food_type', models.CharField(max_length=200)),
                ('food_image', models.FileField(upload_to='food_image')),
            ],
            options={
                'db_table': 'food',
            },
        ),
    ]
